name = "r2-download-bug"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[build]
command = "cargo install --git https://github.com/cloudflare/workers-rs.git -q worker-build && worker-build --release"

[[r2_buckets]]
binding = "BIN"
bucket_name = "r2-download-bug"

[[env.local.r2_buckets]]
binding = "BIN"
bucket_name = "r2-download-bug"
preview_bucket_name = "preview-r2-download-bug"